### ISSUE TITLE
Not recognizing use of CSS selectors on `Col`

### ISSUE THREAD

**Issue by jtlapp** [bestguy/sveltestrap#400]
Is there a way to get sveltestrap to recognize the use of local CSS selectors?

For example, I have this in my HTML and CSS:

```html
<Col class="title">{title}</Col>
```

```css
  .title {
    margin-bottom: 1em;
    font-weight: bold;
  }
```

But Svelte gives me an "Unused CSS selector" warning.

Do I need to disable this warning to use sveltestrap?
