### ISSUE TITLE
Should `color` prop type definitions allow arbitrary string values?

### ISSUE THREAD

**Issue by ohmree** [bestguy/sveltestrap#453]
With the following sass that generates a new button variant:
```scss
// src/app.scss
// include this however you like.
@import 'bootstrap';

$twitch-purple: #9146ff;
.btn-twitch {
  @include button-variant($twitch-purple, $twitch-purple);
}
```
I can do `<Button color="twitch" />` and get the expected behavior (a purple button) - except typescript complains about `'twitch'` not being a valid value for this prop.
Should components that accept color/variant props allow arbitrary strings for cases like this?
There are other ways to make the button look the way I want it to in this case but I think they're both inferior:
 - `<Button class="btn-twitch" />` - compiles to an element with both `btn-secondary` and `btn-twitch`, which looks like I want it to in practice but I feel like might interfere with some tools that do tree-shaking (plus the unnecessary class just bothers me).
 - Manually styling the element - tedious and error-prone, you'd either be duplicating the `button-variant` mixin or have an inconsistently styled element (e.g. if you style just the background and text colors, you might end up with the default border color from `.btn-secondary`).
